<?php

use Illuminate\Database\Seeder;
use App\Answer;

class AnswersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Answer::truncate();
		$answers = [
			/*Automotive*/
			['question_id' => '1', 'answer' => 'Car (Sedan or Convertible)'],
			['question_id' => '1', 'answer' => 'Car (SUV)'],
			['question_id' => '1', 'answer' => 'Van'],
			['question_id' => '1', 'answer' => 'Pickup truck'],
			['question_id' => '1', 'answer' => 'Lorry'],


			['question_id' => '2', 'answer' => 'ACURA'],
			['question_id' => '2', 'answer' => 'ALFA ROMEO'],
			['question_id' => '2', 'answer' => 'AMC'],
			['question_id' => '2', 'answer' => 'ARIEL'],
			['question_id' => '2', 'answer' => 'ASTON MARTIN'],
			['question_id' => '2', 'answer' => 'AUDI'],
			['question_id' => '2', 'answer' => 'AUSTIN HEALEY'],
			['question_id' => '2', 'answer' => 'BENTLEY'],
			['question_id' => '2', 'answer' => 'BMW'],
			['question_id' => '2', 'answer' => 'BUGATTI'],
			['question_id' => '2', 'answer' => 'BUICK'],
			['question_id' => '2', 'answer' => 'CADILLAC'],
			['question_id' => '2', 'answer' => 'CALLAWAY'],
			['question_id' => '2', 'answer' => 'CATERHAM'],
			['question_id' => '2', 'answer' => 'CHEVROLET'],
			['question_id' => '2', 'answer' => 'CHRYSLER'],
			['question_id' => '2', 'answer' => 'CITROEN'],
			['question_id' => '2', 'answer' => 'DAEWOO'],
			['question_id' => '2', 'answer' => 'DAIHATSU'],
			['question_id' => '2', 'answer' => 'DATSUN'],
			['question_id' => '2', 'answer' => 'DE TOMASO'],
			['question_id' => '2', 'answer' => 'DODGE'],
			['question_id' => '2', 'answer' => 'EAGLE'],
			['question_id' => '2', 'answer' => 'FERRARI'],
			['question_id' => '2', 'answer' => 'FIAT'],
			['question_id' => '2', 'answer' => 'FISKER'],
			['question_id' => '2', 'answer' => 'FORD'],
			['question_id' => '2', 'answer' => 'GEO'],
			['question_id' => '2', 'answer' => 'GMC'],
			['question_id' => '2', 'answer' => 'HOLDEN'],
			['question_id' => '2', 'answer' => 'HONDA'],
			['question_id' => '2', 'answer' => 'HUMMER'],
			['question_id' => '2', 'answer' => 'HYUNDAI'],
			['question_id' => '2', 'answer' => 'INFINITI'],
			['question_id' => '2', 'answer' => 'ISUZU'],
			['question_id' => '2', 'answer' => 'JAGUAR'],
			['question_id' => '2', 'answer' => 'JEEP'],
			['question_id' => '2', 'answer' => 'KIA'],
			['question_id' => '2', 'answer' => 'KOENIGSEGG'],
			['question_id' => '2', 'answer' => 'LAMBORGHINI'],
			['question_id' => '2', 'answer' => 'LANCIA'],
			['question_id' => '2', 'answer' => 'LAND ROVER'],
			['question_id' => '2', 'answer' => 'LEXUS'],
			['question_id' => '2', 'answer' => 'LINCOLN'],
			['question_id' => '2', 'answer' => 'LOTUS'],
			['question_id' => '2', 'answer' => 'MASERATI'],
			['question_id' => '2', 'answer' => 'MAYBACH'],
			['question_id' => '2', 'answer' => 'MAZDA'],
			['question_id' => '2', 'answer' => 'MCLAREN'],
			['question_id' => '2', 'answer' => 'MERCEDES'],
			['question_id' => '2', 'answer' => 'MERCURY'],
			['question_id' => '2', 'answer' => 'MG'],
			['question_id' => '2', 'answer' => 'MINI'],
			['question_id' => '2', 'answer' => 'MITSUBISHI'],
			['question_id' => '2', 'answer' => 'MORGAN'],
			['question_id' => '2', 'answer' => 'MOSLER / ROSSION'],
			['question_id' => '2', 'answer' => 'NISSAN'],
			['question_id' => '2', 'answer' => 'NOBLE'],
			['question_id' => '2', 'answer' => 'OLDSMOBILE'],
			['question_id' => '2', 'answer' => 'OPEL'],
			['question_id' => '2', 'answer' => 'PAGANI'],
			['question_id' => '2', 'answer' => 'PEUGEOT'],
			['question_id' => '2', 'answer' => 'PLYMOUTH'],
			['question_id' => '2', 'answer' => 'PONTIAC'],
			['question_id' => '2', 'answer' => 'PORSCHE'],
			['question_id' => '2', 'answer' => 'PROTON'],
			['question_id' => '2', 'answer' => 'RAM'],
			['question_id' => '2', 'answer' => 'RENAULT'],
			['question_id' => '2', 'answer' => 'ROLLS-ROYCE'],
			['question_id' => '2', 'answer' => 'SAAB'],
			['question_id' => '2', 'answer' => 'SALEEN'],
			['question_id' => '2', 'answer' => 'SATURN'],
			['question_id' => '2', 'answer' => 'SCION'],
			['question_id' => '2', 'answer' => 'SEAT'],
			['question_id' => '2', 'answer' => 'SHELBY'],
			['question_id' => '2', 'answer' => 'SKODA'],
			['question_id' => '2', 'answer' => 'SMART'],
			['question_id' => '2', 'answer' => 'SSANGYONG'],
			['question_id' => '2', 'answer' => 'SUBARU'],
			['question_id' => '2', 'answer' => 'SUZUKI'],
			['question_id' => '2', 'answer' => 'TESLA'],
			['question_id' => '2', 'answer' => 'TOYOTA'],
			['question_id' => '2', 'answer' => 'TRIUMPH'],
			['question_id' => '2', 'answer' => 'VAUXHALL'],
			['question_id' => '2', 'answer' => 'VOLKSWAGEN'],
			['question_id' => '2', 'answer' => 'VOLVO'],
			['question_id' => '2', 'answer' => 'WESTFIELD'],

			['question_id' => '3', 'answer' => 'Engine'],
			['question_id' => '3', 'answer' => 'Chassis'],
			['question_id' => '3', 'answer' => 'Bodywork (Denting & Painting)'],
			['question_id' => '3', 'answer' => 'Tyres'],
			['question_id' => '3', 'answer' => 'Interiors & Carpeting'],
			['question_id' => '3', 'answer' => 'Audio Visual systems'],
			['question_id' => '3', 'answer' => 'Battery'],
			['question_id' => '3', 'answer' => 'Brakes'],
			['question_id' => '3', 'answer' => 'Suspension & Shock Absorbers'],

			['question_id' => '4', 'answer' => 'Regular Servicing & Check-Up'],
			['question_id' => '4', 'answer' => 'Cleaning & Washing'],
			['question_id' => '4', 'answer' => 'Waxing & Polishing'],
			['question_id' => '4', 'answer' => 'Repair'],
			['question_id' => '4', 'answer' => 'Spares & Replacement'],
			['question_id' => '4', 'answer' => 'Restoration'],


			/*Airconditioning*/
			['question_id' => '5', 'answer' => 'Regular service and maintenance'],
			['question_id' => '5', 'answer' => 'Gas refilling and checking of coolant level'],
			['question_id' => '5', 'answer' => 'Cleaning of split & ducted air cooling systems'],
			['question_id' => '5', 'answer' => 'Installation of a new airconditioning system'],
			['question_id' => '5', 'answer' => 'Cleaning or replacement of filter driers & air filters'],
			['question_id' => '5', 'answer' => 'Inspecting and/or replacing of copper piping insulation'],
			['question_id' => '5', 'answer' => 'Checking of running pressures & temperatures'],
			['question_id' => '5', 'answer' => 'Checking of the compressor’s power usage'],
			['question_id' => '5', 'answer' => 'Leak repair'],
			['question_id' => '5', 'answer' => 'Freeze repair'],
			['question_id' => '5', 'answer' => 'Not sure, I need an inspection'],

			['question_id' => '6', 'answer' => 'Split aircon'],
			['question_id' => '6', 'answer' => 'Standup aircon'],
			['question_id' => '6', 'answer' => 'Ceilling/ Cassette aircon'],
			['question_id' => '6', 'answer' => 'Central aircon'],

			['question_id' => '7', 'answer' => '0.5 Tons'],
			['question_id' => '7', 'answer' => '1 Ton'],
			['question_id' => '7', 'answer' => '1.5 Tons'],
			['question_id' => '7', 'answer' => '2 Tons'],
			['question_id' => '7', 'answer' => '2.5 Tons'],
			['question_id' => '7', 'answer' => 'Need a recommendation'],

			['question_id' => '8', 'answer' => '1 to 25'],
			['question_id' => '8', 'answer' => '26 to 50'],
			['question_id' => '8', 'answer' => '51 to 75'],
			['question_id' => '8', 'answer' => '76 to 100'],


			['question_id' => '9', 'answer' => 'Residential Apartment'],
			['question_id' => '9', 'answer' => 'Independent House / Villa / Bungalow'],
			['question_id' => '9', 'answer' => 'Business / Office Property'],
			['question_id' => '9', 'answer' => 'Commercial Complex / Mall'],
			['question_id' => '9', 'answer' => 'Residential Complex'],
			['question_id' => '9', 'answer' => 'Medical Facility / Hospital'],
			['question_id' => '9', 'answer' => 'Restaurant'],
			['question_id' => '9', 'answer' => 'School'],
			['question_id' => '9', 'answer' => 'Highrise Building'],
			['question_id' => '9', 'answer' => 'Hotel / Service Apartment'],
			['question_id' => '9', 'answer' => 'Factory'],

			['question_id' => '10', 'answer' => 'Less than 500'],
			['question_id' => '10', 'answer' => 'Between 501 and 1000'],
			['question_id' => '10', 'answer' => 'Between 1001 and 2000'],
			['question_id' => '10', 'answer' => 'Betweeen 2001 and 3000'],
			['question_id' => '10', 'answer' => 'Between 3001 and 4000'],
			['question_id' => '10', 'answer' => 'Between 4001 and 5000'],
			['question_id' => '10', 'answer' => 'Between 5001 and 10000'],
			['question_id' => '10', 'answer' => 'Greater than 10000'],


			/*Beauty and styling*/
			['question_id' => '11', 'answer' => 'Makeup Artist'],
			['question_id' => '11', 'answer' => 'Beautician'],
			['question_id' => '11', 'answer' => 'Hair Stylist'],

			['question_id' => '12', 'answer' => 'Wedding (I am the bride)'],
			['question_id' => '12', 'answer' => 'Fashion Show'],
			['question_id' => '12', 'answer' => 'Engagement'],
			['question_id' => '12', 'answer' => 'Pre-wedding'],
			['question_id' => '12', 'answer' => 'Photo/ Video Shoot'],
			['question_id' => '12', 'answer' => 'Party'],
			['question_id' => '12', 'answer' => 'Corporate Event'],
			['question_id' => '12', 'answer' => 'Musical / Theatre'],
			['question_id' => '12', 'answer' => 'Lunch/ Dinner Reception'],
			['question_id' => '12', 'answer' => 'Family function'],

			['question_id' => '13', 'answer' => 'Customer hair pieces'],
			['question_id' => '13', 'answer' => 'Hair extensions / rebonding'],
			['question_id' => '13', 'answer' => 'Hair trimming / hair cut'],
			['question_id' => '13', 'answer' => 'Hair smoothening'],
			['question_id' => '13', 'answer' => 'Hair styling'],
			['question_id' => '13', 'answer' => 'Hair Spa'],
			['question_id' => '13', 'answer' => 'Hair coloring'],
			['question_id' => '13', 'answer' => 'Tiara'],
			['question_id' => '13', 'answer' => 'Makeup primer'],
			['question_id' => '13', 'answer' => 'Airbrushed makeup'],
			['question_id' => '13', 'answer' => 'Tattoo covering'],
			['question_id' => '13', 'answer' => 'Natural / Simple makeup'],
			['question_id' => '13', 'answer' => 'Romantic makeup'],
			['question_id' => '13', 'answer' => 'Glamourous and bold makeup'],
			['question_id' => '13', 'answer' => 'Elegant makeup'],
			['question_id' => '13', 'answer' => 'Smokey eyes makeup'],
			['question_id' => '13', 'answer' => 'Body shimmer'],
			['question_id' => '13', 'answer' => 'Body foundation'],
			['question_id' => '13', 'answer' => 'False eyelashes'],
			['question_id' => '13', 'answer' => 'Eyebrow shaping'],
			['question_id' => '13', 'answer' => 'Facial'],
			['question_id' => '13', 'answer' => 'Waxing '],
			['question_id' => '13', 'answer' => 'Bleaching'],
			['question_id' => '13', 'answer' => 'Manicure '],
			['question_id' => '13', 'answer' => 'Pedicure'],
			['question_id' => '13', 'answer' => 'Threading'],
			['question_id' => '13', 'answer' => 'Massage'],
			['question_id' => '13', 'answer' => 'Henna application'],
			['question_id' => '13', 'answer' => 'Spa treatment'],

			['question_id' => '14', 'answer' => '1'],
			['question_id' => '14', 'answer' => '2'],
			['question_id' => '14', 'answer' => '3'],
			['question_id' => '14', 'answer' => '4'],
			['question_id' => '14', 'answer' => '5'],
			['question_id' => '14', 'answer' => '> 6'],

			/*Borehole drilling*/
			['question_id' => '16', 'answer' => 'Not sure'],
			['question_id' => '16', 'answer' => '20m'],
			['question_id' => '16', 'answer' => '25m'],
			['question_id' => '16', 'answer' => '30m'],
			['question_id' => '16', 'answer' => '35m'],
			['question_id' => '16', 'answer' => '40m'],
			['question_id' => '16', 'answer' => '45m'],

			/*Carpentry*/
			['question_id' => '17', 'answer' => 'Build'],
			['question_id' => '17', 'answer' => 'Replace or repair'],
			['question_id' => '17', 'answer' => 'Install'],
			['question_id' => '17', 'answer' => 'Uninstall or remove'],

			['question_id' => '18', 'answer' => 'Furniture'],
			['question_id' => '18', 'answer' => 'Walls'],
			['question_id' => '18', 'answer' => 'Shelves'],
			['question_id' => '18', 'answer' => 'Deck'],
			['question_id' => '18', 'answer' => 'Gazebo'],
			['question_id' => '18', 'answer' => 'Door'],
			['question_id' => '18', 'answer' => 'Windows'],
			['question_id' => '18', 'answer' => 'Stairs'],



			['question_id' => '20', 'answer' => 'Yes, I will provide the materials and parts'],
			['question_id' => '20', 'answer' => 'Yes, but I will need guidance from the provider'],
			['question_id' => '20', 'answer' => 'No, I will need the provider to provide the materials and parts'],
			

			/*Cleaning and House keeping*/
			['question_id' => '21', 'answer' => 'Residential Apartment'],
			['question_id' => '21', 'answer' => 'Independent House / Villa / Bungalow'],
			['question_id' => '21', 'answer' => 'Business / Office Property'],
			['question_id' => '21', 'answer' => 'Commercial Complex / Mall'],
			['question_id' => '21', 'answer' => 'Residential Complex'],
			['question_id' => '21', 'answer' => 'Medical Facility / Hospital'],
			['question_id' => '21', 'answer' => 'Restaurant'],
			['question_id' => '21', 'answer' => 'School'],
			['question_id' => '21', 'answer' => 'Highrise Building'],
			['question_id' => '21', 'answer' => 'Hotel / Service Apartment'],
			['question_id' => '21', 'answer' => 'Factory'],

			['question_id' => '22', 'answer' => 'Windows'],
			['question_id' => '22', 'answer' => 'Exterior Surface / Building façade'],
			['question_id' => '22', 'answer' => 'Signboard & Lighting'],
			['question_id' => '22', 'answer' => 'Skylight'],
			['question_id' => '22', 'answer' => 'Swimming Pool'],
			['question_id' => '22', 'answer' => 'Floor'],
			['question_id' => '22', 'answer' => 'Carpets'],
			['question_id' => '22', 'answer' => 'Upholstery'],
			['question_id' => '22', 'answer' => 'Garden / Patio / Verandah / Wooden Deck'],
			['question_id' => '22', 'answer' => 'Bathrooms'],
			['question_id' => '22', 'answer' => 'Common Areas (Corridors etc.)'],
			['question_id' => '22', 'answer' => 'Jacuzzi / Spa '],
			['question_id' => '22', 'answer' => 'Walls'],
			['question_id' => '22', 'answer' => 'Bedrooms / Rooms'],
			['question_id' => '22', 'answer' => 'Terrace / Roof'],
			['question_id' => '22', 'answer' => 'Warehouse / Store'],
			['question_id' => '22', 'answer' => 'Basement'],
			['question_id' => '22', 'answer' => 'Kitchen / Pantry'],

			['question_id' => '23', 'answer' => 'Less than 500'],
			['question_id' => '23', 'answer' => 'Between 501 and 1000'],
			['question_id' => '23', 'answer' => 'Between 1001 and 2000'],
			['question_id' => '23', 'answer' => 'Betweeen 2001 and 3000'],
			['question_id' => '23', 'answer' => 'Between 3001 and 4000'],
			['question_id' => '23', 'answer' => 'Between 4001 and 5000'],
			['question_id' => '23', 'answer' => 'Between 5001 and 10000'],
			['question_id' => '23', 'answer' => 'Greater than 10000'],

			['question_id' => '24', 'answer' => 'Just one time '],
			['question_id' => '24', 'answer' => 'Everyday'],
			['question_id' => '24', 'answer' => 'Once a week'],
			['question_id' => '24', 'answer' => 'More than once a week'],
			['question_id' => '24', 'answer' => 'Once a month'],
			['question_id' => '24', 'answer' => 'Once in 6 months'],
			['question_id' => '24', 'answer' => 'I need a recommendation'],

			['question_id' => '25', 'answer' => 'Yes, I will provide the equipment and supplies'],
			['question_id' => '25', 'answer' => 'Yes, but I will need guidance from the provider'],
			['question_id' => '25', 'answer' => 'No, I will need the provider to provide the equipment and supplies'],

			/*Computer,Hardware & Peripherals*/
			['question_id' => '26', 'answer' => 'CPU'],
			['question_id' => '26', 'answer' => 'Laptop'],
			['question_id' => '26', 'answer' => 'Tablet'],
			['question_id' => '26', 'answer' => 'Printer'],
			['question_id' => '26', 'answer' => 'Keyboard'],
			['question_id' => '26', 'answer' => 'Screen'],
			['question_id' => '26', 'answer' => 'Headphones'],
			['question_id' => '26', 'answer' => 'Audio Speakers'],
			['question_id' => '26', 'answer' => 'Server'],
			['question_id' => '26', 'answer' => 'Ports (Flash / USB / SATA/ VGA etc)'],
			['question_id' => '26', 'answer' => 'Hard Drive'],
			['question_id' => '26', 'answer' => 'Routers / Switches'],
			['question_id' => '26', 'answer' => 'CD-ROM drive'],
			['question_id' => '26', 'answer' => 'DVD drive'],
			['question_id' => '26', 'answer' => 'VoIP Telephony'],

			['question_id' => '27', 'answer' => 'Acer'],
			['question_id' => '27', 'answer' => 'Amazon'],
			['question_id' => '27', 'answer' => 'Astro'],
			['question_id' => '27', 'answer' => 'ASUS'],
			['question_id' => '27', 'answer' => 'Blue Gate'],
			['question_id' => '27', 'answer' => 'Bryte'],
			['question_id' => '27', 'answer' => 'Dell'],
			['question_id' => '27', 'answer' => 'Fero'],
			['question_id' => '27', 'answer' => 'Fire'],
			['question_id' => '27', 'answer' => 'Google '],
			['question_id' => '27', 'answer' => 'HP'],
			['question_id' => '27', 'answer' => 'Huawei'],
			['question_id' => '27', 'answer' => 'IBM'],
			['question_id' => '27', 'answer' => 'Infinix'],
			['question_id' => '27', 'answer' => 'InnJoo'],
			['question_id' => '27', 'answer' => 'Karborn'],
			['question_id' => '27', 'answer' => 'Lenovo'],
			['question_id' => '27', 'answer' => 'Microsoft'],
			['question_id' => '27', 'answer' => 'Motorola'],
			['question_id' => '27', 'answer' => 'Proline'],
			['question_id' => '27', 'answer' => 'Samsung'],
			['question_id' => '27', 'answer' => 'Sansui'],
			['question_id' => '27', 'answer' => 'Sony'],
			['question_id' => '27', 'answer' => 'Techno'],
			['question_id' => '27', 'answer' => 'Toshiba'],


			['question_id' => '29', 'answer' => 'Not sure, need guidance'],
			['question_id' => '29', 'answer' => 'Hardware update/repair'],
			['question_id' => '29', 'answer' => 'Software update/repair'],
			['question_id' => '29', 'answer' => 'Screen is cracked or damaged'],
			['question_id' => '29', 'answer' => 'Virus or malware removal'],
			['question_id' => '29', 'answer' => 'Connecting to the Internet'],
			['question_id' => '29', 'answer' => 'Connecting devices'],
			['question_id' => '29', 'answer' => 'Computer will not turn on'],
			['question_id' => '29', 'answer' => 'Ports not functioning'],
			['question_id' => '29', 'answer' => 'Sound problem'],
			['question_id' => '29', 'answer' => 'Hard disk problem / crash'],
			['question_id' => '29', 'answer' => 'Data Recovery / Back up'],
			['question_id' => '29', 'answer' => 'Server side trouble shooting / Server down'],
			['question_id' => '29', 'answer' => 'Telecommunication down '],
			['question_id' => '29', 'answer' => 'Printer not working / connecting'],

			['question_id' => '30', 'answer' => 'Legacy Windows: Windows 98, Windows 3.11, etc'],
			['question_id' => '30', 'answer' => 'Windows XP'],
			['question_id' => '29', 'answer' => 'Windows VistaWindows 7Windows 8'],
			['question_id' => '30', 'answer' => 'Windows 7Windows 8'],
			['question_id' => '30', 'answer' => 'Windows 8'],
			['question_id' => '30', 'answer' => 'Windows 10'],
			['question_id' => '30', 'answer' => 'Legacy Mac OS 9 and below'],
			['question_id' => '30', 'answer' => 'Mac OS X Lion and before'],
			['question_id' => '30', 'answer' => 'Mac OS X Mountain Lion'],
			['question_id' => '30', 'answer' => 'Mac OS X Mavericks'],
			['question_id' => '30', 'answer' => 'Mac OS X Yosemite'],
			['question_id' => '30', 'answer' => 'Mac OS X El Capitan'],
			['question_id' => '30', 'answer' => 'Android'],
			['question_id' => '30', 'answer' => 'LINUX'],
			['question_id' => '30', 'answer' => 'Not sure, need guidance'],

			['question_id' => '31', 'answer' => 'Personal'],
			['question_id' => '31', 'answer' => 'Business or non-profit'],
			['question_id' => '31', 'answer' => 'School / Educational'],
			['question_id' => '31', 'answer' => 'Government / Public service'],


			/*Consumer Appliances & Gadgets*/
			['question_id' => '32', 'answer' => 'Washer / dryer'],
			['question_id' => '32', 'answer' => 'Water Heater / Geyser'],
			['question_id' => '32', 'answer' => 'Electronic Watch'],
			['question_id' => '32', 'answer' => 'Refrigerator'],
			['question_id' => '32', 'answer' => 'Outdoor tools (lawn mower, etc.)'],
			['question_id' => '32', 'answer' => 'Oven / stove'],
			['question_id' => '32', 'answer' => 'Dishwasher'],
			['question_id' => '32', 'answer' => 'Fax machine / EPABX'],
			['question_id' => '32', 'answer' => 'Cordless phone'],
			['question_id' => '32', 'answer' => 'Desk phone'],
			['question_id' => '32', 'answer' => 'Microwave oven'],
			['question_id' => '32', 'answer' => 'Vacuum cleaner'],
			['question_id' => '32', 'answer' => 'Television'],
			['question_id' => '32', 'answer' => 'DVD player'],
			['question_id' => '32', 'answer' => 'Home Music System'],
			['question_id' => '32', 'answer' => 'CD Player'],
			['question_id' => '32', 'answer' => 'Portable Music Player'],
			['question_id' => '32', 'answer' => 'Headphones'],
			['question_id' => '32', 'answer' => 'Audio Speakers'],



			['question_id' => '34', 'answer' => 'Regular Servicing & Check-Up'],
			['question_id' => '34', 'answer' => 'Repair'],
			['question_id' => '34', 'answer' => 'Spares & Replacement'],
			['question_id' => '34', 'answer' => 'Restoration'],


			/*Electrical & Wiring*/
			['question_id' => '35', 'answer' => 'Install new fitting'],
			['question_id' => '35', 'answer' => 'Replace or Repair - Loss of Power / Inconsistent Power'],
			['question_id' => '35', 'answer' => 'Replace or Repair - Sparking'],
			['question_id' => '35', 'answer' => 'Replace or Repair - Warm / Burning Smell'],
			['question_id' => '35', 'answer' => 'Replace or Repair - Fixture not working'],
			['question_id' => '35', 'answer' => 'Not sure, I need an inspection'],

			['question_id' => '36', 'answer' => 'Lights'],
			['question_id' => '36', 'answer' => 'Switches'],
			['question_id' => '36', 'answer' => 'Outlets / Sockets'],
			['question_id' => '36', 'answer' => 'Mains'],
			['question_id' => '36', 'answer' => 'Circuit breaker panel or fuse box'],
			['question_id' => '36', 'answer' => 'Wiring'],
			['question_id' => '36', 'answer' => 'Ceiling Fan'],
			['question_id' => '36', 'answer' => 'Exhaust Fan'],
			['question_id' => '36', 'answer' => 'Airconditioning Unit'],
			['question_id' => '36', 'answer' => 'Consumer Appliance (Fridge, Oven, Microwave, TV etc.)'],
			['question_id' => '36', 'answer' => 'Transformer (internal or external)'],
			['question_id' => '36', 'answer' => 'Power Conversion Unit'],
			['question_id' => '36', 'answer' => 'Electric motor'],
			['question_id' => '36', 'answer' => 'Generator'],
			['question_id' => '36', 'answer' => 'Inverter'],
			['question_id' => '36', 'answer' => 'Outdoor wiring'],
			['question_id' => '36', 'answer' => 'Entire facility'],
			['question_id' => '36', 'answer' => 'Not sure, need guidance'],

			['question_id' => '37', 'answer' => 'Residential Apartment'],
			['question_id' => '37', 'answer' => 'Independent House / Villa / Bungalow'],
			['question_id' => '37', 'answer' => 'Business / Office Property'],
			['question_id' => '37', 'answer' => 'Commercial Complex / Mall'],
			['question_id' => '37', 'answer' => 'Residential Complex'],
			['question_id' => '37', 'answer' => 'Medical Facility / Hospital'],
			['question_id' => '37', 'answer' => 'Restaurant'],
			['question_id' => '37', 'answer' => 'School'],
			['question_id' => '37', 'answer' => 'Highrise Building'],
			['question_id' => '37', 'answer' => 'Hotel / Service Apartment'],
			['question_id' => '37', 'answer' => 'Factory'],

			['question_id' => '38', 'answer' => 'Washroom'],
			['question_id' => '38', 'answer' => 'Kitchen'],
			['question_id' => '38', 'answer' => 'Garage'],
			['question_id' => '38', 'answer' => 'Concealed / False Ceiling'],
			['question_id' => '38', 'answer' => 'Store'],
			['question_id' => '38', 'answer' => 'Basement'],
			['question_id' => '38', 'answer' => 'Behind the walls'],
			['question_id' => '38', 'answer' => 'Outdoor / Street'],
			['question_id' => '38', 'answer' => 'Below the floor / underground'],

			['question_id' => '39', 'answer' => 'Yes, I will provide the materials and parts'],
			['question_id' => '39', 'answer' => 'Yes, but I will need guidance from the provider'],
			['question_id' => '39', 'answer' => 'No, I will need the provider to provide the materials and parts'],


			/*Fencing*/
			['question_id' => '40', 'answer' => 'Install new fence '],
			['question_id' => '40', 'answer' => 'Remove old and replace with new fence'],
			['question_id' => '40', 'answer' => 'Repair old fence - water damage leaks'],
			['question_id' => '40', 'answer' => 'Repair old fence - missing boards'],
			['question_id' => '40', 'answer' => 'Repair old fence - repainting'],
			['question_id' => '40', 'answer' => 'Repair old fence - cracked or damaged boards'],
			['question_id' => '40', 'answer' => 'Repair old fence - sagging'],
			['question_id' => '40', 'answer' => 'Repair old fence - wood rot'],
			['question_id' => '40', 'answer' => 'Repair old fence - rusting'],
			['question_id' => '40', 'answer' => 'Repair old fence - gate damage'],
			['question_id' => '40', 'answer' => 'Routine cleaning and maintenance'],
			['question_id' => '40', 'answer' => 'Not sure, I need an inspection'],

			['question_id' => '41', 'answer' => 'Under 4 feet'],
			['question_id' => '41', 'answer' => '4 feet'],
			['question_id' => '41', 'answer' => '5 feet'],
			['question_id' => '41', 'answer' => '6 feet'],
			['question_id' => '41', 'answer' => '7 feet'],
			['question_id' => '41', 'answer' => '8 feet'],
			['question_id' => '41', 'answer' => 'Over 8 feet'],
			['question_id' => '41', 'answer' => 'Not sure, need guidance'],

			['question_id' => '42', 'answer' => 'Wood'],
			['question_id' => '42', 'answer' => 'Vinyl'],
			['question_id' => '42', 'answer' => 'Aluminum'],
			['question_id' => '42', 'answer' => 'Steel'],
			['question_id' => '42', 'answer' => 'Chain link'],
			['question_id' => '42', 'answer' => 'Wrought Iron'],
			['question_id' => '42', 'answer' => 'Not sure, need guidance'],

			['question_id' => '43', 'answer' => 'Independent House / Villa / Bungalow'],
			['question_id' => '43', 'answer' => 'Business / Office Property'],
			['question_id' => '43', 'answer' => 'Commercial Complex / Mall'],
			['question_id' => '43', 'answer' => 'Residential Complex'],
			['question_id' => '43', 'answer' => 'Medical Facility / Hospital'],
			['question_id' => '43', 'answer' => 'Restaurant'],
			['question_id' => '43', 'answer' => 'School'],
			['question_id' => '43', 'answer' => 'Highrise Building'],
			['question_id' => '43', 'answer' => 'Hotel / Service Apartment'],
			['question_id' => '43', 'answer' => 'Factory'],

			['question_id' => '44', 'answer' => 'Under 50 feet'],
			['question_id' => '44', 'answer' => '50-100 feet'],
			['question_id' => '44', 'answer' => '100-150 feet'],
			['question_id' => '44', 'answer' => '150-200 feet'],
			['question_id' => '44', 'answer' => '200-250 feet'],
			['question_id' => '44', 'answer' => 'Over 250 feet'],
			['question_id' => '44', 'answer' => 'Not sure, need guidance'],

			['question_id' => '45', 'answer' => 'Yes, I will provide the materials and parts'],
			['question_id' => '45', 'answer' => 'Yes, but I will need guidance from the provider'],
			['question_id' => '45', 'answer' => 'No, I will need the provider to provide the materials and parts'],


			['question_id' => '46', 'answer' => 'Install new floor or tiles'],
			['question_id' => '46', 'answer' => 'Remove old and replace with new floor or tiles - complete'],
			['question_id' => '46', 'answer' => 'Remove old and replace with new floor otr tiles - partial'],
			['question_id' => '46', 'answer' => 'Repair old floor or tiles - cupping or buckling'],
			['question_id' => '46', 'answer' => 'Repair old floor or tiles - cracked or splintering'],
			['question_id' => '46', 'answer' => 'Repair old floor or tiles - uneven or bumps'],
			['question_id' => '46', 'answer' => 'Repair old floor or tiles - scratched or worn'],
			['question_id' => '46', 'answer' => 'Repair old floor or tiles - loosening '],
			['question_id' => '46', 'answer' => 'Repair old fence or tiles - discoloration or paint staining'],
			['question_id' => '46', 'answer' => 'Routine cleaning, polishing and maintenance'],
			['question_id' => '46', 'answer' => 'Not sure, I need an inspection'],

			['question_id' => '47', 'answer' => 'Laminate'],
			['question_id' => '47', 'answer' => 'Solid wood'],
			['question_id' => '47', 'answer' => 'Engineered hardwood'],
			['question_id' => '47', 'answer' => 'Bamboo'],
			['question_id' => '47', 'answer' => 'Marble'],
			['question_id' => '47', 'answer' => 'Carpet'],
			['question_id' => '47', 'answer' => 'Linoleum or vinyl'],
			['question_id' => '47', 'answer' => 'Vitrified Tiles'],
			['question_id' => '47', 'answer' => 'Stone'],
			['question_id' => '47', 'answer' => 'Vinyl'],
			['question_id' => '47', 'answer' => 'Concrete'],
			['question_id' => '47', 'answer' => 'Not sure, need guidance'],

			['question_id' => '48', 'answer' => 'Basic smooth trowel finish'],
			['question_id' => '48', 'answer' => 'Polished'],
			['question_id' => '48', 'answer' => 'Brush textured, slip-resistant'],
			['question_id' => '48', 'answer' => 'Special color or other additive'],
			['question_id' => '48', 'answer' => 'Lightweight concrete'],
			['question_id' => '48', 'answer' => 'Cast / molded to look like stone or tile'],
			['question_id' => '48', 'answer' => 'Not sure, need guidance'],

			['question_id' => '49', 'answer' => 'Independent House / Villa / Bungalow'],
			['question_id' => '49', 'answer' => 'Business / Office Property'],
			['question_id' => '49', 'answer' => 'Commercial Complex / Mall'],
			['question_id' => '49', 'answer' => 'Residential Complex'],
			['question_id' => '49', 'answer' => 'Medical Facility / Hospital'],
			['question_id' => '49', 'answer' => 'Restaurant'],
			['question_id' => '49', 'answer' => 'School'],
			['question_id' => '49', 'answer' => 'Highrise Building'],
			['question_id' => '49', 'answer' => 'Hotel / Service Apartment'],
			['question_id' => '49', 'answer' => 'Factory'],

			['question_id' => '50', 'answer' => 'Less than 500'],
			['question_id' => '50', 'answer' => 'Between 501 and 1000'],
			['question_id' => '50', 'answer' => 'Between 1001 and 2000'],
			['question_id' => '50', 'answer' => 'Betweeen 2001 and 3000'],
			['question_id' => '50', 'answer' => 'Between 3001 and 4000'],
			['question_id' => '50', 'answer' => 'Between 4001 and 5000'],
			['question_id' => '50', 'answer' => 'Between 5001 and 10000'],
			['question_id' => '50', 'answer' => 'Greater than 10000'],
			['question_id' => '50', 'answer' => 'Not sure, need guidance'],

			['question_id' => '51', 'answer' => 'Room(s) not in a rectangular or square shape'],
			['question_id' => '51', 'answer' => 'Fixtures on the wall'],
			['question_id' => '51', 'answer' => 'Supports and fixtures installed into floor'],
			['question_id' => '51', 'answer' => 'Tiling in the kitchen wall or floor with appliances'],
			['question_id' => '51', 'answer' => 'Tiling in the bathroom wall or floor with fixtures'],
			['question_id' => '51', 'answer' => 'Stairs'],

			['question_id' => '52', 'answer' => 'Yes, I will provide the materials and parts'],
			['question_id' => '52', 'answer' => 'Yes, but I will need guidance from the provider'],
			['question_id' => '52', 'answer' => 'No, I will need the provider to provide the materials and parts'],

			/*Food & beverage catering*/
			['question_id' => '53', 'answer' => 'Office / Commercial catering - recurring'],
			['question_id' => '53', 'answer' => 'Corporate event'],
			['question_id' => '53', 'answer' => 'Baby shower'],
			['question_id' => '53', 'answer' => 'Wedding reception'],
			['question_id' => '53', 'answer' => 'Birthday party'],
			['question_id' => '53', 'answer' => 'Graduation party'],
			['question_id' => '53', 'answer' => 'Bridal shower'],
			['question_id' => '53', 'answer' => 'Children s party'],
			['question_id' => '53', 'answer' => 'House party'],
			['question_id' => '53	', 'answer' => 'Family get together'],

			['question_id' => '54', 'answer' => 'Full meal'],
			['question_id' => '54', 'answer' => 'Appetizer(s)'],
			['question_id' => '54', 'answer' => 'Hors d oeuvre(s)'],
			['question_id' => '54', 'answer' => 'Finger food(s)'],
			['question_id' => '54', 'answer' => 'Main course(s)'],
			['question_id' => '54', 'answer' => 'Side dish(es)'],
			['question_id' => '54', 'answer' => 'Dessert(s)'],
			['question_id' => '54', 'answer' => 'Cold beverages (non-alcoholic)'],
			['question_id' => '54', 'answer' => 'Cold beverages (alcoholic)'],
			['question_id' => '54', 'answer' => 'Fruits'],
			['question_id' => '54', 'answer' => 'Hot beverages (coffee, tea)'],

			['question_id' => '55', 'answer' => 'African (Traditional)'],
			['question_id' => '55', 'answer' => 'Italian'],
			['question_id' => '55', 'answer' => 'Mexican'],
			['question_id' => '55', 'answer' => 'Mediterranean / Middle Eastern'],
			['question_id' => '55', 'answer' => 'South Asian (Indian)'],
			['question_id' => '55', 'answer' => 'Far Eastern (Japanese, Chinese)'],
			['question_id' => '55', 'answer' => 'South East Asian (Thai, Indonesian, Vietnamese)'],
			['question_id' => '55', 'answer' => 'Western (American / British)'],
			['question_id' => '55', 'answer' => 'German'],
			['question_id' => '55', 'answer' => 'French'],
			['question_id' => '55', 'answer' => 'Spanish'],

			['question_id' => '56', 'answer' => 'Served / full table setup - with server(s)'],
			['question_id' => '56', 'answer' => 'Served / full table setup - without server(s), just setup only'],
			['question_id' => '56', 'answer' => 'Only Food & Berverages Drop-Off - no service'],
			['question_id' => '56', 'answer' => 'Only Bartending services'],
			['question_id' => '56', 'answer' => 'Buffet / Self-Service'],
			['question_id' => '56', 'answer' => 'Food stations'],

			['question_id' => '57', 'answer' => 'Fewer than 20'],
			['question_id' => '57', 'answer' => '20-50'],
			['question_id' => '57', 'answer' => '50-100'],
			['question_id' => '57', 'answer' => '100-150'],
			['question_id' => '57', 'answer' => '150-200'],
			['question_id' => '57', 'answer' => 'More than 200'],

			['question_id' => '58', 'answer' => 'Just one time'],
			['question_id' => '58', 'answer' => 'Daily'],
			['question_id' => '58', 'answer' => 'Weekly'],
			['question_id' => '58', 'answer' => 'Bi-Weekly'],
			['question_id' => '58', 'answer' => 'Monthly'],
			['question_id' => '58', 'answer' => 'Once a month'],


			/*Gardening & Landscaping*/
			['question_id' => '59', 'answer' => 'Gardening - create new on dirt'],
			['question_id' => '59', 'answer' => 'Gardening - replace existing'],
			['question_id' => '59', 'answer' => 'Gardening - maintain existing'],
			['question_id' => '59', 'answer' => 'Outdoor Landscaping - create new on dirt'],
			['question_id' => '59', 'answer' => 'Outdoor Landscaping - replace existing'],
			['question_id' => '59', 'answer' => 'Outdoor Landscaping - update part of existing'],
			['question_id' => '59', 'answer' => 'No idea, I want a recommendation'],

			['question_id' => '60', 'answer' => 'Plant watering & care'],
			['question_id' => '60', 'answer' => 'Planting / removing grass'],
			['question_id' => '60', 'answer' => 'Planting / removing shrubs'],
			['question_id' => '60', 'answer' => 'Planting trees / removing trees'],
			['question_id' => '60', 'answer' => 'Planting flower bed / removing flower bed'],
			['question_id' => '60', 'answer' => 'Sprinkler installation'],
			['question_id' => '60', 'answer' => 'Drainage system'],
			['question_id' => '60', 'answer' => 'Outdoor lighting'],
			['question_id' => '60', 'answer' => 'Boulders / Stones'],
			['question_id' => '60', 'answer' => 'Water features'],
			['question_id' => '60', 'answer' => 'Artificial grass / turf'],
			['question_id' => '60', 'answer' => 'Mowing'],
			['question_id' => '60', 'answer' => 'Leaf clean up'],
			['question_id' => '60', 'answer' => 'Mulching'],
			['question_id' => '60', 'answer' => 'Insect Control'],
			['question_id' => '60', 'answer' => 'Aeration'],
			['question_id' => '60', 'answer' => 'Weeding'],
			['question_id' => '60', 'answer' => 'Trimming & Edging'],
			['question_id' => '60', 'answer' => 'Seeding'],
			['question_id' => '60', 'answer' => 'Fertilizing'],
			['question_id' => '60', 'answer' => 'I want a recommendation'],

			['question_id' => '61', 'answer' => 'Residential Apartment'],
			['question_id' => '61', 'answer' => 'Independent House / Villa / Bungalow'],
			['question_id' => '61', 'answer' => 'Business / Office Property'],
			['question_id' => '61', 'answer' => 'Commercial Complex / Mall'],
			['question_id' => '61', 'answer' => 'Residential Complex'],
			['question_id' => '61', 'answer' => 'Medical Facility / Hospital'],
			['question_id' => '61', 'answer' => 'Restaurant'],
			['question_id' => '61', 'answer' => 'School'],
			['question_id' => '61', 'answer' => 'Highrise Building'],
			['question_id' => '61', 'answer' => 'Hotel / Service Apartment'],
			['question_id' => '61', 'answer' => 'Factory'],

			['question_id' => '62', 'answer' => 'Front yard'],
			['question_id' => '62', 'answer' => 'Back yard'],
			['question_id' => '62', 'answer' => 'Side yard'],
			['question_id' => '62', 'answer' => 'Terrace / Roof'],
			['question_id' => '62', 'answer' => 'Kitchen Garden'],
			['question_id' => '62', 'answer' => 'Inside the facility / Indoors'],

			['question_id' => '63', 'answer' => 'Less than 500'],
			['question_id' => '63', 'answer' => 'Between 501 and 1000'],
			['question_id' => '63', 'answer' => 'Between 1001 and 2000'],
			['question_id' => '63', 'answer' => 'Betweeen 2001 and 3000'],
			['question_id' => '63', 'answer' => 'Between 3001 and 4000'],
			['question_id' => '63', 'answer' => 'Between 4001 and 5000'],
			['question_id' => '63', 'answer' => 'Between 5001 and 10000'],
			['question_id' => '63', 'answer' => 'Greater than 10000'],

			['question_id' => '64', 'answer' => 'Just one time'],
			['question_id' => '64', 'answer' => 'Everyday'],
			['question_id' => '64', 'answer' => 'Once a week'],
			['question_id' => '64', 'answer' => 'More than once a week'],
			['question_id' => '64', 'answer' => 'Once a month'],
			['question_id' => '64', 'answer' => 'Once in 6 months'],
			['question_id' => '64', 'answer' => 'I need a recommendation'],


			/*Househelp & Maids*/
			['question_id' => '65', 'answer' => 'Housemaid'],
			['question_id' => '65', 'answer' => 'Cook'],
			['question_id' => '65', 'answer' => 'Nurse / Homecare '],
			['question_id' => '65', 'answer' => 'Driver'],
			['question_id' => '65', 'answer' => 'Baby Sitter / Nanny'],

			['question_id' => '66', 'answer' => 'Full-time / Permanent - Resident with you'],
			['question_id' => '66', 'answer' => 'Full-time / Permanent - Non-resident with you'],
			['question_id' => '66', 'answer' => 'Part-time - Once in a week '],
			['question_id' => '66', 'answer' => 'Part-time - More than once a week '],
			['question_id' => '66', 'answer' => 'Part-time - Once in a month'],
			['question_id' => '66', 'answer' => 'Just one time'],

			['question_id' => '67', 'answer' => 'I do not have any expectations'],
			['question_id' => '67', 'answer' => 'High school degree'],
			['question_id' => '67', 'answer' => 'College Degree and/ or higher'],

			['question_id' => '68', 'answer' => 'No experience is required'],
			['question_id' => '68', 'answer' => '1 to 2 years'],
			['question_id' => '68', 'answer' => '2 to 5 years'],
			['question_id' => '68', 'answer' => '5 to 10 years'],
			['question_id' => '68', 'answer' => '10 years +'],


			['question_id' => '69', 'answer' => 'Mobile phone'],
			['question_id' => '69', 'answer' => 'Tablet'],
			['question_id' => '69', 'answer' => 'ebook Readers'],

			['question_id' => '70', 'answer' => 'Android'],	
			['question_id' => '70', 'answer' => 'iOS'],	
			['question_id' => '70', 'answer' => 'Blackberry'],	
			['question_id' => '70', 'answer' => 'Windows'],	
			['question_id' => '70', 'answer' => 'Kindle'],	
			['question_id' => '70', 'answer' => 'I do not know'],				

			['question_id' => '71', 'answer' => 'Acer'],	
			['question_id' => '71', 'answer' => 'Amazon'],
			['question_id' => '71', 'answer' => 'Astro'],
			['question_id' => '71', 'answer' => 'ASUS'],
			['question_id' => '71', 'answer' => 'Blue Gate'],
			['question_id' => '71', 'answer' => 'Bryte'],
			['question_id' => '71', 'answer' => 'Dell'],
			['question_id' => '71', 'answer' => 'Fero'],
			['question_id' => '71', 'answer' => 'Fire'],
			['question_id' => '71', 'answer' => 'Google'],
			['question_id' => '71', 'answer' => 'HP'],
			['question_id' => '71', 'answer' => 'Huawei'],
			['question_id' => '71', 'answer' => 'IBM'],
			['question_id' => '71', 'answer' => 'Infinix'],
			['question_id' => '71', 'answer' => 'InnJoo'],
			['question_id' => '71', 'answer' => 'Karborn'],
			['question_id' => '71', 'answer' => 'Lenovo'],
			['question_id' => '71', 'answer' => 'Microsoft'],
			['question_id' => '71', 'answer' => 'Motorola'],
			['question_id' => '71', 'answer' => 'Proline'],
			['question_id' => '71', 'answer' => 'Samsung'],
			['question_id' => '71', 'answer' => 'Sansui'],
			['question_id' => '71', 'answer' => 'Sony'],
			['question_id' => '71', 'answer' => 'Techno'],
			['question_id' => '71', 'answer' => 'Toshiba'],
			['question_id' => '71', 'answer' => 'Universal'],



			['question_id' => '73', 'answer' => 'Water damage'],
			['question_id' => '73', 'answer' => 'Broken or cracked screen - screen replacement'],
			['question_id' => '73', 'answer' => 'Hardware issues'],
			['question_id' => '73', 'answer' => 'Applications won t work/install'],
			['question_id' => '73', 'answer' => 'Reformatting phone'],
			['question_id' => '73', 'answer' => 'Frozen phone'],
			['question_id' => '73', 'answer' => 'Data recovery'],
			['question_id' => '73', 'answer' => 'Device nor working at all'],
			['question_id' => '73', 'answer' => 'Wifi not working'],
			['question_id' => '73', 'answer' => 'Bluetooth problem'],
			['question_id' => '73', 'answer' => 'Sound problem'],
			['question_id' => '73', 'answer' => 'Charging problem'],
			['question_id' => '73', 'answer' => 'Operating System (OS) issue'],
			['question_id' => '73', 'answer' => 'Battery issue'],
			['question_id' => '73', 'answer' => 'Heating problem'],
			['question_id' => '73', 'answer' => 'Software update/repair'],
			['question_id' => '73', 'answer' => 'Hardware update/repair'],


			/*Packing & Moving*/
			['question_id' => '76', 'answer' => 'Specific items'],
			['question_id' => '76', 'answer' => 'Residential Apartment - 1 Bedroom'],
			['question_id' => '76', 'answer' => 'Residential Apartment - 2 Bedroom'],
			['question_id' => '76', 'answer' => 'Residential Apartment - 3 Bedroom'],
			['question_id' => '76', 'answer' => 'Residential Apartment - 4 and more Bedrooms'],
			['question_id' => '76', 'answer' => 'Independent House / Villa - 1 Bedroom'],
			['question_id' => '76', 'answer' => 'Independent House / Villa - 2 Bedroom'],
			['question_id' => '76', 'answer' => 'Independent House / Villa - 3 Bedroom'],
			['question_id' => '76', 'answer' => 'Independent House / Villa - 4 and more Bedrooms'],
			['question_id' => '76', 'answer' => 'Business / Office Property'],
			['question_id' => '76', 'answer' => 'Studio'],

			['question_id' => '77', 'answer' => 'Disassembly / Dismantling current location'],
			['question_id' => '77', 'answer' => 'Packing into boxes'],
			['question_id' => '77', 'answer' => 'Large furniture, household items moving'],
			['question_id' => '77', 'answer' => 'Transportation / Shfiting from current to destination location'],
			['question_id' => '77', 'answer' => 'Reassembly at destination location'],
			['question_id' => '77', 'answer' => 'Supply of boxes / containers'],
			['question_id' => '77', 'answer' => 'Additional manpower / workers'],
			['question_id' => '77', 'answer' => 'Transportation via Lorry / Truck'],
			['question_id' => '77', 'answer' => 'Storage services'],
			['question_id' => '77', 'answer' => 'Handyman services '],
			['question_id' => '77', 'answer' => 'Insurance'],

			['question_id' => '78', 'answer' => 'Less than 1 ton '],
			['question_id' => '78', 'answer' => 'Between 1 ton and 3 ton'],
			['question_id' => '78', 'answer' => 'Between 3 ton and 5 ton'],
			['question_id' => '78', 'answer' => 'Between 5 ton and 10 ton'],
			['question_id' => '78', 'answer' => 'Greater than 10 ton'],
			['question_id' => '78', 'answer' => 'Not sure, I need a survey'],

			['question_id' => '79', 'answer' => 'There are no stairs, it is on ground floor'],
			['question_id' => '79', 'answer' => 'There are stairs, I am on floor no.'],
			['question_id' => '79', 'answer' => 'There is an elevator / lift'],

			['question_id' => '80', 'answer' => 'There are no stairs, it is on ground floor'],
			['question_id' => '80', 'answer' => 'There are stairs, I am on floor no.'],
			['question_id' => '80', 'answer' => 'There is an elevator / lift'],

			/*Pest control*/
			['question_id' => '81', 'answer' => 'Cockroaches'],
			['question_id' => '81', 'answer' => 'Ants'],
			['question_id' => '81', 'answer' => 'Bed bugs'],
			['question_id' => '81', 'answer' => 'Rodents'],
			['question_id' => '81', 'answer' => 'Bees, Hornets or Wasps'],
			['question_id' => '81', 'answer' => 'Fleas, Ticks or Mites'],
			['question_id' => '81', 'answer' => 'Termites'],
			['question_id' => '81', 'answer' => 'Spiders'],
			['question_id' => '81', 'answer' => 'Mosquitoes'],
			['question_id' => '81', 'answer' => 'I am not sure'],

			['question_id' => '82', 'answer' => 'Inspection'],
			['question_id' => '82', 'answer' => 'Removal or extermination'],
			['question_id' => '82', 'answer' => 'Preventative measures'],

			['question_id' => '83', 'answer' => 'Residential Apartment'],
			['question_id' => '83', 'answer' => 'Independent House / Villa / Bungalow'],
			['question_id' => '83', 'answer' => 'Business / Office Property'],
			['question_id' => '83', 'answer' => 'Commercial Complex / Mall'],
			['question_id' => '83', 'answer' => 'Residential Complex'],
			['question_id' => '83', 'answer' => 'Medical Facility / Hospital'],
			['question_id' => '83', 'answer' => 'Restaurant'],
			['question_id' => '83', 'answer' => 'School'],
			['question_id' => '83', 'answer' => 'Highrise Building'],
			['question_id' => '83', 'answer' => 'Hotel / Service Apartment'],
			['question_id' => '83', 'answer' => 'Factory'],

			['question_id' => '84', 'answer' => 'Less than 500'],
			['question_id' => '84', 'answer' => 'Between 501 and 1000'],
			['question_id' => '84', 'answer' => 'Between 1001 and 2000'],
			['question_id' => '84', 'answer' => 'Betweeen 2001 and 3000'],
			['question_id' => '84', 'answer' => 'Between 3001 and 4000'],
			['question_id' => '84', 'answer' => 'Between 4001 and 5000'],
			['question_id' => '84', 'answer' => 'Between 5001 and 10000'],
			['question_id' => '84', 'answer' => 'Greater than 10000'],

			['question_id' => '85', 'answer' => 'Windows'],
			['question_id' => '85', 'answer' => 'Furniture'],
			['question_id' => '85', 'answer' => 'Floor'],
			['question_id' => '85', 'answer' => 'Carpets'],
			['question_id' => '85', 'answer' => 'Upholstery'],
			['question_id' => '85', 'answer' => 'Garden / Patio / Verandah / Wooden Deck'],
			['question_id' => '85', 'answer' => 'Bathrooms'],
			['question_id' => '85', 'answer' => 'Common Areas (Corridors etc.)'],
			['question_id' => '85', 'answer' => 'Walls'],
			['question_id' => '85', 'answer' => 'Bedrooms / Rooms'],
			['question_id' => '85', 'answer' => 'Terrace / Roof'],
			['question_id' => '85', 'answer' => 'Attic'],
			['question_id' => '85', 'answer' => 'Warehouse / Store'],
			['question_id' => '85', 'answer' => 'Kitchen / Pantry'],
			['question_id' => '85', 'answer' => 'Basement'],


			/*Photography & Video Filming*/
			['question_id' => '86', 'answer' => 'Commercial (Product, Portrait, Landscape, Travel, Industrial, Business etc)'],
			['question_id' => '86', 'answer' => 'Conference'],
			['question_id' => '86', 'answer' => 'Office Event'],
			['question_id' => '86', 'answer' => 'Sports Game'],
			['question_id' => '86', 'answer' => 'Wedding Event'],
			['question_id' => '86', 'answer' => 'Birthday Event'],
			['question_id' => '86', 'answer' => 'Family Pictures '],
			['question_id' => '86', 'answer' => 'Life Event'],
			['question_id' => '86', 'answer' => 'Corporate Event'],
			['question_id' => '86', 'answer' => 'Children s Event'],

			['question_id' => '87', 'answer' => 'Traditional photography (e.g., posed, looking directly in the camera)'],
			['question_id' => '87', 'answer' => 'Candid photography (e.g., captured in the moment)'],
			['question_id' => '87', 'answer' => 'Artistic photigraphy (focus on composition and lighting)'],
			['question_id' => '87', 'answer' => 'Normal videofilming with lightingHigh Fashion photography'],
			['question_id' => '87', 'answer' => 'Music video'],
			['question_id' => '87', 'answer' => 'Short film'],
			['question_id' => '87', 'answer' => 'Full length movie'],

			['question_id' => '88', 'answer' => '1 - 3 hours'],
			['question_id' => '88', 'answer' => '3 - 6 hours'],
			['question_id' => '88', 'answer' => '6 - 8 hours'],
			['question_id' => '88', 'answer' => '8 - 10 hours'],
			['question_id' => '88', 'answer' => 'More than 10 hours'],

			['question_id' => '89', 'answer' => '< 20 people'],
			['question_id' => '89', 'answer' => '20 to 50 people'],
			['question_id' => '89', 'answer' => '50 to 100 people'],
			['question_id' => '89', 'answer' => '100 to 150 people'],
			['question_id' => '89', 'answer' => '150 to 250 people'],
			['question_id' => '89', 'answer' => '> 200 people'],

			['question_id' => '90', 'answer' => 'Home'],
			['question_id' => '90', 'answer' => 'Outdoor (Rooftop / Garden)'],
			['question_id' => '90', 'answer' => 'Office'],
			['question_id' => '90', 'answer' => 'Photographer s Studio'],
			['question_id' => '90', 'answer' => 'Restaurant / Café '],
			['question_id' => '90', 'answer' => 'Hotel Ballroom'],
			['question_id' => '90', 'answer' => 'Not yet sure'],

			['question_id' => '91', 'answer' => 'CD/ DVD / Memory stick/ card'],
			['question_id' => '91', 'answer' => 'Online or digital proofs and print'],
			['question_id' => '91', 'answer' => 'Physical proofs and print'],
			['question_id' => '91', 'answer' => 'Ability to purchase prints online'],
			['question_id' => '91', 'answer' => 'Copies for editorial use'],
			['question_id' => '91', 'answer' => 'Large display units (e.g. trade shows)'],
			['question_id' => '91', 'answer' => 'Website hosting'],
			['question_id' => '91', 'answer' => 'Print or catalogues (for advertising)'],
			['question_id' => '91', 'answer' => 'Album'],
			['question_id' => '91', 'answer' => 'Raw footage'],
			['question_id' => '91', 'answer' => 'Professionally edited video'],
			['question_id' => '91', 'answer' => 'Full feature video (30 to 40 minutes)'],
			['question_id' => '91', 'answer' => 'Highlight video (3 to 4 minutes)'],
			['question_id' => '91', 'answer' => 'Not yet sure'],


			/*Plumbing & Drainage*/
			['question_id' => '92', 'answer' => 'Install new fitting'],
			['question_id' => '92', 'answer' => 'Replace or Repair - Leaking / burst pipe'],
			['question_id' => '92', 'answer' => 'Replace or Repair - Clogged drain'],
			['question_id' => '92', 'answer' => 'Replace or Repair - Low water / no pressure'],
			['question_id' => '92', 'answer' => 'Replace or Repair - Fixture not draining / flushing'],
			['question_id' => '92', 'answer' => 'Replace or Repair - Unpleasent Odour'],
			['question_id' => '92', 'answer' => 'Not sure, I need an inspection'],

			['question_id' => '93', 'answer' => 'Pipes / Drains'],
			['question_id' => '93', 'answer' => 'Toilet bowl'],
			['question_id' => '93', 'answer' => 'Sink / basin'],
			['question_id' => '93', 'answer' => 'Shower head'],
			['question_id' => '93', 'answer' => 'Shower'],
			['question_id' => '93', 'answer' => 'Bathtub'],
			['question_id' => '93', 'answer' => 'Basin mixer'],
			['question_id' => '93', 'answer' => 'Water pump'],
			['question_id' => '93', 'answer' => 'Washer / Dryer'],
			['question_id' => '93', 'answer' => 'Dishwasher'],
			['question_id' => '93', 'answer' => 'Water heater'],
			['question_id' => '93', 'answer' => 'Water treatment system'],
			['question_id' => '93', 'answer' => 'Septic system'],
			['question_id' => '93', 'answer' => 'Borewell '],
			['question_id' => '93', 'answer' => 'Sump pump'],
			['question_id' => '93', 'answer' => 'Well system'],
			['question_id' => '93', 'answer' => 'Outdoor plumbing'],
			['question_id' => '93', 'answer' => 'Entire facility'],
			['question_id' => '93', 'answer' => 'Not sure, need guidance'],

			['question_id' => '94', 'answer' => 'Residential Apartment'],
			['question_id' => '94', 'answer' => 'Independent House / Villa / Bungalow'],
			['question_id' => '94', 'answer' => 'Business / Office Property'],
			['question_id' => '94', 'answer' => 'Commercial Complex / Mall'],
			['question_id' => '94', 'answer' => 'Residential Complex'],
			['question_id' => '94', 'answer' => 'RestaurantMedical Facility / Hospital'],
			['question_id' => '94', 'answer' => 'School'],
			['question_id' => '94', 'answer' => 'Highrise Building'],
			['question_id' => '94', 'answer' => 'Hotel / Service Apartment'],
			['question_id' => '94', 'answer' => 'Factory'],

			['question_id' => '95', 'answer' => 'Washroom'],
			['question_id' => '95', 'answer' => 'Kitchen'],
			['question_id' => '95', 'answer' => 'Garage'],
			['question_id' => '95', 'answer' => 'Concealed / False Ceiling'],
			['question_id' => '95', 'answer' => 'Behind the walls'],
			['question_id' => '95', 'answer' => 'Store'],
			['question_id' => '95', 'answer' => 'Basement'],
			['question_id' => '95', 'answer' => 'Outdoor / Street'],
			['question_id' => '95', 'answer' => 'Below the floor / underground	'],

			['question_id' => '96', 'answer' => 'Yes, I will provide the materials and parts'],
			['question_id' => '96', 'answer' => 'Yes, but I will need guidance from the provider'],
			['question_id' => '96', 'answer' => 'No, I will need the provider to provide the materials and parts'],


			/*Printing & Design*/
			['question_id' => '97', 'answer' => 'Printing'],
			['question_id' => '97', 'answer' => 'Graphic Design'],
			['question_id' => '97', 'answer' => 'Binding'],
			['question_id' => '97', 'answer' => 'Photocopying'],

			['question_id' => '98', 'answer' => 'Backdrop'],
			['question_id' => '98', 'answer' => 'Calendar'],
			['question_id' => '98', 'answer' => 'Order / Quotation Book'],
			['question_id' => '98', 'answer' => 'Receipt Book'],
			['question_id' => '98', 'answer' => 'Greeting Card'],
			['question_id' => '98', 'answer' => 'Envelope'],
			['question_id' => '98', 'answer' => 'Hang Tag'],
			['question_id' => '98', 'answer' => 'Menu'],
			['question_id' => '98', 'answer' => 'Certificates'],
			['question_id' => '98', 'answer' => 'Banner'],
			['question_id' => '98', 'answer' => 'Diaries'],
			['question_id' => '98', 'answer' => 'Brochures / Flyers'],
			['question_id' => '98', 'answer' => 'Newsletter'],
			['question_id' => '98', 'answer' => 'Invitations'],
			['question_id' => '98', 'answer' => 'Business card / Letterhead'],
			['question_id' => '98', 'answer' => 'Magazine / Catalog'],
			['question_id' => '98', 'answer' => 'Banner'],
			['question_id' => '98', 'answer' => 'Poster'],
			['question_id' => '98', 'answer' => 'Logo / Branding'],
			['question_id' => '98', 'answer' => 'Business Materials / Presentation (in PowerPoint)'],

			['question_id' => '99', 'answer' => 'Personal'],
			['question_id' => '99', 'answer' => 'Business or non-profit'],
			['question_id' => '99', 'answer' => 'School / Educational'],
			['question_id' => '99', 'answer' => 'Government / Public service'],

			['question_id' => '100', 'answer' => '1 to 100'],
			['question_id' => '100', 'answer' => '100 - 200'],
			['question_id' => '100', 'answer' => '201 - 300'],
			['question_id' => '100', 'answer' => '301 - 400'],
			['question_id' => '100', 'answer' => '401 - 500'],
			['question_id' => '100', 'answer' => '501 - 1000'],
			['question_id' => '100', 'answer' => '1001 - 2000'],
			['question_id' => '100', 'answer' => '2001 - 3000'],
			['question_id' => '100', 'answer' => '3001 and above'],

			['question_id' => '101', 'answer' => 'A0 (33.1 × 46.8 in)'],
			['question_id' => '101', 'answer' => 'A1 (23.4 × 33.1 in)'],
			['question_id' => '101', 'answer' => 'A2 (16.5 × 23.4 in)'],
			['question_id' => '101', 'answer' => 'A3 (11.7 × 16.5 in)'],
			['question_id' => '101', 'answer' => 'A4 (8.3 × 11.7 in)'],
			['question_id' => '101', 'answer' => 'A5 (5.8 × 8.3 in)'],
			['question_id' => '101', 'answer' => 'A6 (4.1 × 5.8 in)'],
			['question_id' => '101', 'answer' => 'A7 (2.9 × 4.1 in)'],
			['question_id' => '101', 'answer' => 'A8 (2.0 × 2.9 in)'],
			['question_id' => '101', 'answer' => 'A9 (1.5 × 2.0 in)'],
			['question_id' => '101', 'answer' => 'A10 (1.0 × 1.5 in)'],
			['question_id' => '101', 'answer' => 'Business Card'],
			['question_id' => '101', 'answer' => 'Letter (8.5 × 11 in)'],
			['question_id' => '101', 'answer' => 'Legal (8.5 × 14.0 in)'],
			['question_id' => '101', 'answer' => 'Postcard (4 X 6 in)'],
			['question_id' => '101', 'answer' => 'C4 Enevelope (9.02 X 12.76 in)'],
			['question_id' => '101', 'answer' => 'Folio (8.5 X 13 in)'],

			['question_id' => '102', 'answer' => 'I know what design I want (please upload a sample using the below listed button)'],
			['question_id' => '102', 'answer' => 'I have some design ideas in mind but I want consultation'],
			['question_id' => '102', 'answer' => 'I need multiple versions of the same design (e.g. different formats to use in different places - horizontal, vertical)'],
			['question_id' => '102', 'answer' => 'I want one design, but I want multiple options to choose from'],
			['question_id' => '102', 'answer' => 'I need different designs for different organizations/businesses'],
			['question_id' => '102', 'answer' => 'I do not need any assistance design '],

			['question_id' => '103', 'answer' => 'Install new roof '],
			['question_id' => '103', 'answer' => 'Remove old and replace with new roof'],
			['question_id' => '103', 'answer' => 'Repair old roof - water damage leaks'],
			['question_id' => '103', 'answer' => 'Repair old roof - missing / damaged shingles'],
			['question_id' => '103', 'answer' => 'Repair old roof - moulds'],
			['question_id' => '103', 'answer' => 'Repair old roof - cracked or damaged'],
			['question_id' => '103', 'answer' => 'Repair old roof - sagging'],
			['question_id' => '103', 'answer' => 'Routine cleaning and maintenance'],
			['question_id' => '103', 'answer' => 'Not sure, I need an inspection'],

			['question_id' => '104', 'answer' => 'Less than 500'],
			['question_id' => '104', 'answer' => 'Between 501 and 1000'],
			['question_id' => '104', 'answer' => 'Between 1001 and 2000'],
			['question_id' => '104', 'answer' => 'Betweeen 2001 and 3000'],
			['question_id' => '104', 'answer' => 'Between 3001 and 4000'],
			['question_id' => '104', 'answer' => 'Between 4001 and 5000'],
			['question_id' => '104', 'answer' => 'Between 5001 and 10000'],
			['question_id' => '104', 'answer' => 'Greater than 10000'],

			['question_id' => '105', 'answer' => 'Asphalt shingles'],
			['question_id' => '105', 'answer' => 'Tile (clay, concrete)'],
			['question_id' => '105', 'answer' => 'Thatched roofing'],
			['question_id' => '105', 'answer' => 'Wood shingles or shakes'],
			['question_id' => '105', 'answer' => 'Slate'],
			['question_id' => '105', 'answer' => 'Metal'],
			['question_id' => '105', 'answer' => 'Not sure, need guidance'],

			['question_id' => '106', 'answer' => 'Independent House / Villa / Bungalow - 1 storey'],
			['question_id' => '106', 'answer' => 'Independent House / Villa / Bungalow - 2 storey'],
			['question_id' => '106', 'answer' => 'Business / Office Property'],
			['question_id' => '106', 'answer' => 'Commercial Complex / Mall'],
			['question_id' => '106', 'answer' => 'Residential Complex'],
			['question_id' => '106', 'answer' => 'Restaurant'],
			['question_id' => '106', 'answer' => 'School'],
			['question_id' => '106', 'answer' => 'Factory'],

			['question_id' => '107', 'answer' => 'All flat and walkable'],
			['question_id' => '107', 'answer' => 'All steep and difficult to navigate'],
			['question_id' => '107', 'answer' => 'Mostly flat with some steep areas'],
			['question_id' => '107', 'answer' => 'Mostly steep with some flat areas'],

			['question_id' => '108', 'answer' => 'None'],
			['question_id' => '108', 'answer' => 'Chimney'],
			['question_id' => '108', 'answer' => 'Pipes'],
			['question_id' => '108', 'answer' => 'Vents'],
			['question_id' => '108', 'answer' => 'Skylights'],
			['question_id' => '108', 'answer' => 'Satellite dishes, antennas'],

			['question_id' => '109', 'answer' => 'Yes, I will provide the materials and parts'],
			['question_id' => '109', 'answer' => 'Yes, but I will need guidance from the provider'],
			['question_id' => '109', 'answer' => 'No, I will need the provider to provide the materials and parts'],

			['question_id' => '110', 'answer' => 'Security Guard Services'],
			['question_id' => '110', 'answer' => 'Security and Alarms Installation / Repair'],

			['question_id' => '111', 'answer' => 'Residential Apartment'],
			['question_id' => '111', 'answer' => 'Independent House / Villa / Bungalow'],
			['question_id' => '111', 'answer' => 'Business / Office Property'],
			['question_id' => '111', 'answer' => 'Commercial Complex / Mall'],
			['question_id' => '111', 'answer' => 'Residential Complex'],
			['question_id' => '111', 'answer' => 'Medical Facility / Hospital'],
			['question_id' => '111', 'answer' => 'Restaurant'],
			['question_id' => '111', 'answer' => 'School'],
			['question_id' => '111', 'answer' => 'Highrise Building'],
			['question_id' => '111', 'answer' => 'Hotel / Service Apartment'],
			['question_id' => '111', 'answer' => 'Factory'],
			['question_id' => '111', 'answer' => 'Event'],
			['question_id' => '111', 'answer' => 'Transit'],

			['question_id' => '112', 'answer' => 'Less than 500'],
			['question_id' => '112', 'answer' => 'Between 501 and 1000'],
			['question_id' => '112', 'answer' => 'Between 1001 and 2000'],
			['question_id' => '112', 'answer' => 'Betweeen 2001 and 3000'],
			['question_id' => '112', 'answer' => 'Between 3001 and 4000'],
			['question_id' => '112', 'answer' => 'Between 4001 and 5000'],
			['question_id' => '112', 'answer' => 'Between 5001 and 10000'],
			['question_id' => '112', 'answer' => 'Greater than 10000'],

			['question_id' => '113', 'answer' => '1 to 25'],
			['question_id' => '113', 'answer' => '26 to 50'],
			['question_id' => '113', 'answer' => '51 to 75'],
			['question_id' => '113', 'answer' => '76 to 100'],

			['question_id' => '114', 'answer' => '1 to 23 hours'],
			['question_id' => '114', 'answer' => '1 to 6 days'],
			['question_id' => '114', 'answer' => '1 to 4 weeks'],
			['question_id' => '114', 'answer' => '1 to 12 months'],

			['question_id' => '115', 'answer' => 'Cameras installation'],
			['question_id' => '115', 'answer' => 'Cameras repair'],
			['question_id' => '115', 'answer' => 'Monitoring system + DVR installation'],
			['question_id' => '115', 'answer' => 'Monitoring system + DVR repair'],
			['question_id' => '115', 'answer' => 'Window or door sensors installation'],
			['question_id' => '115', 'answer' => 'Window or door sensors repair'],
			['question_id' => '115', 'answer' => 'Motion sensors installation'],
			['question_id' => '115', 'answer' => 'Motion sensors repair'],
			['question_id' => '115', 'answer' => 'Smoke alarms installation'],
			['question_id' => '115', 'answer' => 'Smoke alarms repair'],
			['question_id' => '115', 'answer' => 'Carbon monoxide sensors installation'],
			['question_id' => '115', 'answer' => 'Door buzzer and intercom system installation'],
			['question_id' => '115', 'answer' => 'Door buzzer and intercom system repair'],
			['question_id' => '115', 'answer' => 'Remote camera viewing access installation'],
			['question_id' => '115', 'answer' => 'Remote camera viewing access repair'],
			['question_id' => '115', 'answer' => 'Nor sure, need a recommendation'],



			['question_id' => '116', 'answer' => 'Pre-K'],
			['question_id' => '116', 'answer' => 'Kindergarten'],
			['question_id' => '116', 'answer' => '2nd grade1st grade'],
			['question_id' => '116', 'answer' => '3rd grade'],
			['question_id' => '116', 'answer' => '4th grade'],
			['question_id' => '116', 'answer' => '5th grade'],
			['question_id' => '116', 'answer' => '6th grade'],
			['question_id' => '116', 'answer' => '7th grade'],
			['question_id' => '116', 'answer' => '8th grade'],
			['question_id' => '116', 'answer' => '9th grade'],
			['question_id' => '116', 'answer' => '10th grade'],
			['question_id' => '116', 'answer' => '11th grade'],
			['question_id' => '116', 'answer' => '12th grade'],
			['question_id' => '116', 'answer' => 'College'],

			['question_id' => '117', 'answer' => 'Math'],
			['question_id' => '117', 'answer' => 'Languages'],
			['question_id' => '117', 'answer' => 'Science'],
			['question_id' => '117', 'answer' => 'Humanities'],
			['question_id' => '117', 'answer' => 'Arts'],

			['question_id' => '118', 'answer' => 'Improve grades at school'],
			['question_id' => '118', 'answer' => 'Learn new topics and techniques'],
			['question_id' => '118', 'answer' => 'Test preparation'],

			['question_id' => '119', 'answer' => 'Once a week'],
			['question_id' => '119', 'answer' => 'More than once a week'],
			['question_id' => '119', 'answer' => 'Once or twice a month'],
			['question_id' => '119', 'answer' => 'As recommended by the tutor'],

			['question_id' => '120', 'answer' => 'Monday'],
			['question_id' => '120', 'answer' => 'Tuesday'],
			['question_id' => '120', 'answer' => 'Wednesday'],
			['question_id' => '120', 'answer' => 'Thursday'],
			['question_id' => '120', 'answer' => 'Friday'],
			['question_id' => '120', 'answer' => 'Saturday'],
			['question_id' => '120', 'answer' => 'Sunday'],

			['question_id' => '121', 'answer' => 'Early morning (before 9am)'],
			['question_id' => '121', 'answer' => 'Morning (9am to 12pm)'],
			['question_id' => '121', 'answer' => 'Early afternoon (12pm to 3pm)'],
			['question_id' => '121', 'answer' => 'Late afternoon (3pm to 6pm)'],
			['question_id' => '121', 'answer' => 'Evening (after 6pm)'],

			['question_id' => '122', 'answer' => 'No, I prefer a one-on-one session'],
			['question_id' => '122', 'answer' => 'Yes, it is fine'],

			['question_id' => '123', 'answer' => 'Tea/ Lunch/ Dinner Reception'],
			['question_id' => '123', 'answer' => 'Engagement Party'],
			['question_id' => '123', 'answer' => 'Church Reception'],
			['question_id' => '123', 'answer' => 'Registration of Marriage (Court)'],
			['question_id' => '123', 'answer' => 'Nikah ceremony'],
			['question_id' => '123', 'answer' => 'Mehndi ceremony'],
			['question_id' => '123', 'answer' => 'Sangeet ceremony'],

			['question_id' => '124', 'answer' => 'Venue Identification, Selection and Booking'],
			['question_id' => '124', 'answer' => 'Budget Preparation and Consultation'],
			['question_id' => '124', 'answer' => 'Itinerary Planning and Preparation'],
			['question_id' => '124', 'answer' => 'Attendee List Planning and Invitation'],
			['question_id' => '124', 'answer' => 'Design, theme and style advice'],
			['question_id' => '124', 'answer' => 'Vendor Sourcing and Selection'],
			['question_id' => '124', 'answer' => 'Vendor coordination (contracts, payments etc.)'],

			['question_id' => '125', 'answer' => 'Photographer'],
			['question_id' => '125', 'answer' => 'Videographer'],
			['question_id' => '125', 'answer' => 'Makeup Artist'],
			['question_id' => '125', 'answer' => 'Caterer'],
			['question_id' => '125', 'answer' => 'Hairstylist'],
			['question_id' => '125', 'answer' => 'DJ'],
			['question_id' => '125', 'answer' => 'Florist'],
			['question_id' => '125', 'answer' => 'Invitation Cards'],
			['question_id' => '125', 'answer' => 'Cake Designer'],
			['question_id' => '125', 'answer' => 'Bridal Wear'],
			['question_id' => '125', 'answer' => 'Singer/ Band'],
			['question_id' => '125', 'answer' => 'Emcee'],
			['question_id' => '125', 'answer' => 'Wedding Car'],
			['question_id' => '125', 'answer' => 'Decoration, Tent & Equipment hiring'],
			['question_id' => '125', 'answer' => 'Gowns '],
			['question_id' => '125', 'answer' => 'Choreography Lessons'],


			['question_id' => '126', 'answer' => 'Fewer than 20'],
			['question_id' => '126', 'answer' => '20-50'],
			['question_id' => '126', 'answer' => '51-100'],
			['question_id' => '126', 'answer' => '101-150'],
			['question_id' => '126', 'answer' => '151-200'],
			['question_id' => '126', 'answer' => 'More than 200'],

        ];
		foreach ($answers as $answer) {
			Answer::insert([
				$answer
			]);
		}
    }
}
